server:
  port: 8089

spring:
  application:
    name: service-provider
  datasource:
    url: jdbc:mysql://localhost:3306/mybastis?serverTimezone=GMT%2B8
    username: root
    password: root
mybatis:
  type-aliases-package: cn.itcast.provider.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10087/eureka

